GET http://localhost:3001/api/orders HTTP/1.1
Content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NiwiaWF0IjoxNjg1MDYxMzI2LCJleHAiOjE2ODUxNDc3MjZ9.w-uCILcFxj9jiMQIDTZk16xIqZpIaYoOfc2gV92gP3I

###

POST http://localhost:3001/api/orders HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NiwiaWF0IjoxNjg1MDYxMzI2LCJleHAiOjE2ODUxNDc3MjZ9.w-uCILcFxj9jiMQIDTZk16xIqZpIaYoOfc2gV92gP3I
Content-type: application/json

{
    "description" : "Треба поміняти колеса",
    "carId": 25,
    "model": "Fiesta",
    "yearOfProduction": 2017,
    "licensePlateNumber": "AK 9265 AK",
    "visitDate": "2023-05-25T13:06:06.403Z",
    "workshopId": 3,
    "services": [{ "id": 1, "title": "Комп'ютерна діагностика", "price": 200  }, { "id": 10, "title": "Заміна гальмівних дисків", "price": 150  }]
}

###

PATCH http://localhost:3001/api/orders/9/change-status HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjAsImlhdCI6MTY4NTAzMzMyMiwiZXhwIjoxNjg1MTE5NzIyfQ.-HulEKaztRv4faTpIqtL3hAhjnqyjlf9hgJkiEYGjz4
Content-type: application/json

{
    "status" : "Rejected"
}