GET http://localhost:3001/api/orders HTTP/1.1
Content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjUsImlhdCI6MTY4NTAyOTA1NiwiZXhwIjoxNjg1MTE1NDU2fQ.V0F197b6mK5KRbn-yqskyYZ7TtaT8VjgH85x9SpFGxA

###

POST http://localhost:3001/api/orders HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjUsImlhdCI6MTY4NTAyODkxMSwiZXhwIjoxNjg1MTE1MzExfQ.VgmnnXD5Xvogn4K3ev77mfEsPb7jqS0pY5EEZAm30_c
Content-type: application/json

{
    "description" : "Треба поміняти колеса",
    "carId": 25,
    "model": "Fiesta",
    "yearOfProduction": 2017,
    "licensePlateNumber": "AK 9265 AK",
    "visitDate": "2023-05-25T13:06:06.403Z",
    "workshopId": 7,
    "services": [{ "id": 1, "title": "Комп'ютерна діагностика", "price": 200  }, { "id": 10, "title": "Заміна гальмівних дисків", "price": 150  }]
}

###

PATCH http://localhost:3001/api/orders/9/change-status HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjAsImlhdCI6MTY4NTAzMzMyMiwiZXhwIjoxNjg1MTE5NzIyfQ.-HulEKaztRv4faTpIqtL3hAhjnqyjlf9hgJkiEYGjz4
Content-type: application/json

{
    "status" : "Rejected"
}